version: '3.8'

services:
  web:
    build: .
    container_name: cross-site-sources-web
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    container_name: cross-site-sources-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017

volumes:
  mongo: