version: '3.8'

services:
  web:
    build: .
    container_name: cross-site-sources-web
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:latest  # Change to latest if not on M1 mac, or CPU without AVX
    restart: always
    container_name: cross-site-sources-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # TODO: Change all of these to use env vars
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
    logging:
      driver: none

volumes:
  mongo:
